### ISSUE TITLE
Bug dans LinkTitles sur la page d'un webinaire

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/tripleperformance#415]
Sur la page https://wiki.tripleperformance.fr/wiki/Semis_direct_en_Camargue

```
2024-11-04T09:29:43+00:00 - processed     1 of  6112 ( 0%) - index     1 - Semis direct en Camargue
[27fbd1fd58bdb94c888a3d9b] [no req]   TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given
Backtrace:
from /var/www/html/extensions/LinkTitles/includes/Linker.php(115)
#0 /var/www/html/extensions/LinkTitles/includes/Linker.php(115): count(boolean)
#1 /var/www/html/extensions/LinkTitles/includes/Extension.php(116): LinkTitles\Linker->linkContent(LinkTitles\Source, string)
#2 /var/www/html/extensions/LinkTitles/linktitles-cli.php(266): LinkTitles\Extension::processPage(Title, RequestContext, boolean, string)
#3 /var/www/html/extensions/LinkTitles/linktitles-cli.php(166): LinkTitles\Cli->allPages()
#4 /var/www/html/maintenance/includes/MaintenanceRunner.php(309): LinkTitles\Cli->execute()
#5 /var/www/html/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#6 /var/www/html/extensions/LinkTitles/linktitles-cli.php(284): require_once(string)
#7 {main}
```

**Comment by bertrandgorge** [comment]
`php html/extensions/LinkTitles/linktitles-cli.php --page "Semis direct en Camargue"`

**Comment by bertrandgorge** [comment]
J'ai ajouté un test avec un log un peu sale - comme on n'utilise ça qu'en ligne de commande, ça fera le job. En pratique y a une gestion des erreurs qui est différente selon qu'on utilise le processus via un script de maintenant (linktitles-cli) ou via un hook (sur l'enregistrement de la page). Pour bien faire il faudrait lever une exception et la choper plus haut...
